import { CertificateTemplate } from "@/components/certificate-editor/types";

/**
 * GOV Certificate Template - Government Form Style
 * Based on the GOV certificate design from certificate-preview.tsx
 * Adjusted for letter size horizontal (792 x 612 pt)
 */
export function getGovTemplate(classType: string = "DATE"): CertificateTemplate {
  return {
    name: "Government Form (GOV Style)",
    classType: classType,
    pageSize: {
      width: 792, // Letter width in landscape
      height: 612, // Letter height in landscape
      orientation: 'landscape',
    },
    certificatesPerPage: 1,
    background: {
      type: 'color',
      value: '#ffffff',
    },
    textElements: [
      // Header - Title
      {
        id: 'text-header-title',
        content: 'CERTIFICATE OF COMPLETION',
        x: 396, // Center of 792
        y: 80,
        fontSize: 18,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'center',
      },
      {
        id: 'text-header-subtitle',
        content: 'This certificate validates that the named person has successfully completed a',
        x: 396,
        y: 110,
        fontSize: 9,
        fontFamily: 'Times-Italic',
        color: '#7a3a2e',
        align: 'center',
        italic: true,
      },
      {
        id: 'text-course-title',
        content: '{{courseTitle}}',
        x: 396,
        y: 120,
        fontSize: 14,
        fontFamily: 'Times-BoldItalic',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'center',
        italic: true,
      },
      {
        id: 'text-course-subtitle',
        content: 'AN UNDER 25 YOUTHFUL OFFENDER COURSE',
        x: 396,
        y: 140,
        fontSize: 9,
        fontFamily: 'Times-Italic',
        color: '#7a3a2e',
        align: 'center',
        italic: true,
      },

      // Course Time - Centrado
      {
        id: 'text-course-time-label',
        content: 'COURSE TIME:',
        x: 306,
        y: 180,
        fontSize: 10,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-course-time-4hr',
        content: '4hr',
        x: 386,
        y: 180,
        fontSize: 10,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-course-time-6hr',
        content: '6hr',
        x: 436,
        y: 180,
        fontSize: 10,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-course-time-8hr',
        content: '8hr',
        x: 486,
        y: 180,
        fontSize: 10,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'left',
      },

      // Citation/Case No, Court, County, Certificate Number - Labels
      {
        id: 'text-citation-label',
        content: 'Citation/Case No:',
        x: 80,
        y: 210,
        fontSize: 10,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-court-label',
        content: 'Court:',
        x: 320,
        y: 210,
        fontSize: 10,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-county-label',
        content: 'County:',
        x: 470,
        y: 210,
        fontSize: 10,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-cert-number-label',
        content: 'Certificate Number:',
        x: 600,
        y: 210,
        fontSize: 10,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'left',
      },

      // Citation/Case No, Court, County, Certificate Number - Values (same Y as labels)
      {
        id: 'text-citation-value',
        content: '{{citationNumber}}',
        x: 165,
        y: 210,
        fontSize: 10,
        fontFamily: 'Times-Roman',
        color: '#000000',
        align: 'left',
      },
      {
        id: 'text-court-value',
        content: '{{court}}',
        x: 355,
        y: 210,
        fontSize: 10,
        fontFamily: 'Times-Roman',
        color: '#000000',
        align: 'left',
      },
      {
        id: 'text-county-value',
        content: '{{county}}',
        x: 515,
        y: 210,
        fontSize: 10,
        fontFamily: 'Times-Roman',
        color: '#000000',
        align: 'left',
      },
      {
        id: 'text-cert-number-value',
        content: '{{certn}}',
        x: 650,
        y: 225,
        fontSize: 10,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#000000',
        align: 'left',
      },

      // Attendance
      {
        id: 'text-attendance-label',
        content: 'Attendance: (reason other than election)',
        x: 80,
        y: 240,
        fontSize: 10,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-attendance-court',
        content: 'Court Order',
        x: 310,
        y: 240,
        fontSize: 10,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-attendance-volunteer',
        content: 'Volunteer',
        x: 410,
        y: 240,
        fontSize: 10,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-attendance-ticket',
        content: 'Ticket/Citation',
        x: 490,
        y: 240,
        fontSize: 10,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'left',
      },

      // Name
      {
        id: 'text-name-label',
        content: 'NAME:',
        x: 80,
        y: 280,
        fontSize: 12,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-name-first',
        content: '{{firstName}}',
        x: 140,
        y: 280,
        fontSize: 12,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#000000',
        align: 'left',
      },
      {
        id: 'text-name-first-label',
        content: 'FIRST',
        x: 140,
        y: 295,
        fontSize: 8,
        fontFamily: 'Times-Roman',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-name-middle',
        content: '{{middleInitial}}',
        x: 340,
        y: 280,
        fontSize: 12,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#000000',
        align: 'left',
      },
      {
        id: 'text-name-middle-label',
        content: 'MI',
        x: 340,
        y: 295,
        fontSize: 8,
        fontFamily: 'Times-Roman',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-name-last',
        content: '{{lastName}}',
        x: 540,
        y: 280,
        fontSize: 12,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#000000',
        align: 'left',
      },
      {
        id: 'text-name-last-label',
        content: 'LAST',
        x: 540,
        y: 295,
        fontSize: 8,
        fontFamily: 'Times-Roman',
        color: '#c94a3a',
        align: 'left',
      },


      // Drivers License
      {
        id: 'text-license-label',
        content: 'Drivers License No:',
        x: 80,
        y: 350,
        fontSize: 10,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-license-value',
        content: '{{licenseNumber}}',
        x: 205,
        y: 350,
        fontSize: 10,
        fontFamily: 'Times-Roman',
        color: '#000000',
        align: 'left',
      },

      // Completion Date
      {
        id: 'text-completion-label',
        content: 'Completion Date:',
        x: 380,
        y: 350,
        fontSize: 10,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-completion-value',
        content: '{{completionDate}}',
        x: 485,
        y: 350,
        fontSize: 10,
        fontFamily: 'Times-Roman',
        color: '#000000',
        align: 'left',
      },

      // Instructor Signature
      {
        id: 'text-instructor-signature-label',
        content: "Instructor's Signature:",
        x: 80,
        y: 420,
        fontSize: 9,
        fontFamily: 'Times-Roman',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-instructor-signature-value',
        content: '{{instructorSignature}}',
        x: 210,
        y: 420,
        fontSize: 10,
        fontFamily: 'Times-Italic',
        color: '#000000',
        align: 'left',
        italic: true,
      },

      // Instructor School Name
      {
        id: 'text-instructor-school-label',
        content: "Instructor's School Name:",
        x: 430,
        y: 420,
        fontSize: 9,
        fontFamily: 'Times-Roman',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-instructor-school-value',
        content: '{{instructorSchoolName}}',
        x: 580,
        y: 420,
        fontSize: 10,
        fontFamily: 'Times-Roman',
        color: '#000000',
        align: 'left',
      },

      // Footer - Provider Info
      {
        id: 'text-provider-label',
        content: 'COURSE PROVIDER',
        x: 80,
        y: 490,
        fontSize: 8,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-provider-name',
        content: 'DRIVER TRAINING ASSOCIATES, INC.',
        x: 80,
        y: 500,
        fontSize: 8,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-provider-phone',
        content: '1-800-222-9199',
        x: 80,
        y: 510,
        fontSize: 8,
        fontFamily: 'Times-Roman',
        color: '#c94a3a',
        align: 'left',
      },
      {
        id: 'text-school-name',
        content: 'Affordable Driving & Traffic School',
        x: 720,
        y: 488,
        fontSize: 8,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#0000ff',
        align: 'right',
      },
      {
        id: 'text-school-phone',
        content: '(561) 969-0150',
        x: 720,
        y: 502,
        fontSize: 8,
        fontFamily: 'Times-Bold',
        fontWeight: 'bold',
        color: '#0000ff',
        align: 'right',
      },
    ],
    imageElements: [
      // Left Logo
      {
        id: 'image-left-logo',
        url: '/logo-izq.png',
        x: 50,
        y: 70,
        width: 120,
        height: 70,
        grayscale: false,
      },
      // Right Logo
      {
        id: 'image-right-logo',
        url: '/logo-der.png',
        x: 650,
        y: 80,
        width: 80,
        height: 60,
        grayscale: false,
      },
    ],
    shapeElements: [
      // Checkboxes para Course Time
      // Checkbox para 4hr (justo después del texto)
      {
        id: 'checkbox-4hr',
        type: 'rectangle',
        x: 405,
        y: 180,
        width: 12,
        height: 12,
        color: 'transparent',
        borderColor: '#c94a3a',
        borderWidth: 1.5,
      },
      // Checkbox para 6hr (justo después del texto)
      {
        id: 'checkbox-6hr',
        type: 'rectangle',
        x: 455,
        y: 180,
        width: 12,
        height: 12,
        color: 'transparent',
        borderColor: '#c94a3a',
        borderWidth: 1.5,
      },
      // Checkbox para 8hr (justo después del texto)
      {
        id: 'checkbox-8hr',
        type: 'rectangle',
        x: 505,
        y: 180,
        width: 12,
        height: 12,
        color: 'transparent',
        borderColor: '#c94a3a',
        borderWidth: 1.5,
      },
      // Checkboxes para Attendance
      // Checkbox para Court Order (justo después del texto)
      {
        id: 'checkbox-court-order',
        type: 'rectangle',
        x: 375,
        y: 240,
        width: 12,
        height: 12,
        color: 'transparent',
        borderColor: '#c94a3a',
        borderWidth: 1.5,
      },
      // Checkbox para Volunteer (justo después del texto)
      {
        id: 'checkbox-volunteer',
        type: 'rectangle',
        x: 470,
        y: 240,
        width: 12,
        height: 12,
        color: 'transparent',
        borderColor: '#c94a3a',
        borderWidth: 1.5,
      },
      // Checkbox para Ticket/Citation (justo después del texto)
      {
        id: 'checkbox-ticket',
        type: 'rectangle',
        x: 570,
        y: 240,
        width: 12,
        height: 12,
        color: 'transparent',
        borderColor: '#c94a3a',
        borderWidth: 1.5,
      },
    ],
    checkboxElements: [
      // Course Time Checkboxes
      {
        id: 'checkbox-course-time',
        title: 'COURSE TIME',
        x: 305,
        y: 180,
        orientation: 'horizontal',
        options: ['4hr', '6hr', '8hr'],
        variableKey: 'courseTime',
        fontSize: 10,
        fontFamily: 'Times-Bold',
        color: '#c94a3a',
        borderColor: '#c94a3a',
        borderWidth: 1.5,
        checkboxSize: 12,
      },
      // Attendance Checkboxes
      {
        id: 'checkbox-attendance',
        title: 'Attendance',
        x: 305,
        y: 240,
        orientation: 'horizontal',
        options: ['Court Order', 'Volunteer', 'Ticket/Citation'],
        variableKey: 'attendanceReason',
        fontSize: 10,
        fontFamily: 'Times-Bold',
        color: '#c94a3a',
        borderColor: '#c94a3a',
        borderWidth: 1.5,
        checkboxSize: 12,
      },
    ],
    availableVariables: [
      { key: 'firstName', label: 'First Name', example: 'JOHN' },
      { key: 'middleInitial', label: 'Middle Initial', example: 'M' },
      { key: 'lastName', label: 'Last Name', example: 'DOE' },
      { key: 'licenseNumber', label: 'License Number', example: 'D123456789' },
      { key: 'citationNumber', label: 'Citation Number', example: '12345' },
      { key: 'court', label: 'Court', example: 'County Court' },
      { key: 'county', label: 'County', example: 'Palm Beach' },
      { key: 'completionDate', label: 'Completion Date', example: '10/14/2025' },
      { key: 'certn', label: 'Certificate Number', example: '1234' },
      { key: 'courseTitle', label: 'Course Title', example: 'DTA STUDENT TRAFFIC OFFENDER PROGRAM' },
      { key: 'deliveryMode', label: 'Delivery Mode', example: 'In Person Class' },
      { key: 'instructorSignature', label: 'Instructor Signature', example: 'John Smith' },
      { key: 'instructorSchoolName', label: 'Instructor School Name', example: 'ABC Driving School' },
      { key: 'providerName', label: 'Provider Name', example: 'Affordable Driving & Traffic School' },
      { key: 'providerPhone', label: 'Provider Phone', example: '(561) 969-0150' },
      // Checkbox variables - se usan para marcar los checkboxes automáticamente
      { 
        key: 'courseTime', 
        label: 'Course Time', 
        example: '4hr',
        options: ['4hr', '6hr', '8hr']
      },
      { 
        key: 'attendanceReason', 
        label: 'Attendance Reason', 
        example: 'ticket',
        options: ['court_order', 'volunteer', 'ticket']
      },
    ],
    isDefault: false,
    isActive: true,
  };
}

